:hammer: Added missing package
--- stderr: uuv_gazebo_ros_plugins
31
In file included from /__w/Plankton/Plankton/src/plankton/uuv_gazebo_plugins/uuv_gazebo_ros_plugins/src/FinROSPlugin.cpp:22:
32
/__w/Plankton/Plankton/src/plankton/uuv_gazebo_plugins/uuv_gazebo_ros_plugins/include/uuv_gazebo_ros_plugins/FinROSPlugin.h:31:10: fatal error: gazebo_ros/node.hpp: No such file or directory
33
   31 | #include <gazebo_ros/node.hpp>
34
      |          ^~~~~~~~~~~~~~~~~~~~~
35
compilation terminated.
36
gmake[2]: *** [CMakeFiles/uuv_fin_ros_plugin.dir/build.make:76: CMakeFiles/uuv_fin_ros_plugin.dir/src/FinROSPlugin.cpp.o] Error 1
37
gmake[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/uuv_fin_ros_plugin.dir/all] Error 2
38
gmake: *** [Makefile:146: all] Error 2